# Generated by Django 4.0.4 on 2022-05-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
