# Generated by Django 4.0.4 on 2022-05-29 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 29, 18, 14, 57, 227666), null=True),
        ),
    ]
