# Generated by Django 4.0.4 on 2022-05-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_projectdetails_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='start_date',
        ),
    ]
