# Generated by Django 4.0.4 on 2022-05-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_projectdetails_tools_projectdetails_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='tools',
            field=models.ManyToManyField(blank=True, to='website.skill'),
        ),
    ]
